services:
  Mailer_MicroService:
    repo: https://github.com/Vritti-ai/mailer-service/
    branch: dev
  api-gateway-service:
    repo: https://github.com/Vritti-ai/api-gateway-service.git
    branch: master
  common-auditor-agent:
    repo: git@github.com:FootLooseLabs/payment-handeller-agent.git
    branch: master
  common_auth_agent:
    repo: git@github.com:Vritti-ai/common-auth-agent.git
    branch: master
  crm-proposal-manager:
    repo: https://github.com/Vritti-ai/crm-proposal-manager.git
    branch: master
  entity-lifecycle-manager:
    repo: https://github.com/Vritti-ai/entity-lifecycle-manager.git
    branch: master
  file_manager_utils:
    repo: git@github.com:Vritti-ai/file-manager-utils.git
    branch: master
  ideation-notes-manager:
    repo: https://github.com/Vritti-ai/ideation-notes-manager.git
    branch: master
  product-package-manager:
    repo: https://github.com/Vritti-ai/product-package-manager.git
    branch: master
  prompt-executor-agent:
    repo: git@github.com:apratimankur/abstraction-ai-prompter-agent.git
    branch: master
  rtc-webrequest-handler:
    repo: git@github.com:Vritti-ai/rtc.webrequest-handler.git
    branch: rpi
  session-manager-agent:
    repo: https://github.com/Vritti-ai/session-manager-agent.git
    branch: master
  user-account-manager:
    repo: https://github.com/Vritti-ai/user-account-manager.git
    branch: master
  vritti-composer:
    repo: git@github.com:Vritti-ai/content-generator.git
    branch: master
  vritti-composer-export:
    repo: https://github.com/Vritti-ai/composer-export.git
    branch: master
  vritti-composer-journal:
    repo: https://github.com/Vritti-ai/vritti-composer-journal.git
    branch: master
  vritti-control-space-manager:
    repo: https://github.com/Vritti-ai/control-space-manager.git
    branch: master
  vritti-ideator:
    repo: git@github.com:Vritti-ai/mind-manager-agent.git
    branch: master
  vritti-ideator-unrefined:
    repo: https://github.com/Vritti-ai/ideator-unrefined.git
    branch: master
  vritti-lifecycle-orchestrator:
    repo: https://github.com/Vritti-ai/vritti-lifecycle-orchestrator.git
    branch: master
  vritti-organizer:
    repo: https://github.com/Vritti-ai/vritti-organiser.git
    branch: master
  vritti-registry-manager:
    repo: https://github.com/Vritti-ai/registry-manager.git
    branch: master
  vritti-vectorizer:
    repo: https://github.com/Vritti-ai/vritti-vectorizer.git
    branch: master
  webhooks-manager:
    repo: https://github.com/Vritti-ai/rtc-webhooks-manager.git
    branch: master
  iden-engine-core:
    repo: git@github.com:FootLooseLabs/iden-engine-core.git
    branch: master
products:
  wity:
    servers:
      - hostname: vritti-dev-server
        path: /home/ubuntu/agents/
    services:
      - Mailer_MicroService
      - api-gateway-service
      - common-auditor-agent
      - common_auth_agent
      - crm-proposal-manager
      - entity-lifecycle-manager
      - file_manager_utils
      - ideation-notes-manager
      - product-package-manager
      - prompt-executor-agent
      - rtc-webrequest-handler
      - session-manager-agent
      - user-account-manager
      - vritti-composer
      - vritti-composer-export
      - vritti-composer-journal
      - vritti-control-space-manager
      - vritti-ideator
      - vritti-ideator-unrefined
      - vritti-lifecycle-orchestrator
      - vritti-organizer
      - vritti-registry-manager
      - vritti-vectorizer
      - webhooks-manager
  vritti-dogfooding:
    servers:
      - hostname: gcp-vritti-dogfooding
        path: /home/ankur/agents/
    services:
      - common_auth_agent
      - rtc-webrequest-handler
      - iden-engine-core
