# Deployment Registry Example Structure

# Define all services
services:
  service_1_urn:
    repo: git_repo_url_https_or_ssh
    branch: 

  service_2_urn:
    repo: git_repo_url_https_or_ssh
    branch: 

  # and so on

# Define products and their infrastructure
products:
  wity:
    servers:
      - hostname: local_alias_server_name
        path: /home/ubuntu/agents/ #example path
    services:
      - service_1_urn
      # and so on

  gcp-vritti-dogfooding:
    servers:
      - hostname: gcp-vritti-dogfooding
        path: /home/ankur/agents/
    services:
      - service_1_urn
      - service_2_urn
      # and so on
  # and so on